name: Ejecutar script cada minuto

on:
  schedule:
    - cron: "*/5 * * * *"  # Se ejecuta cada 3 minutos
  workflow_dispatch:  # Permite ejecutar manualmente

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt || echo "No hay dependencias que instalar"

      - name: Ejecutar script
        run: python PLOT_PG_EFM_ICA_SWP_GITHUB_GRUPO_3.py

      - name: Commit y push si hay cambios
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Subiendo imagen generada automáticamente" || echo "No hay cambios para commitear"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/rr2021/swp_scripts.git HEAD:main
