name: Ejecutar script cada minuto

on:
  schedule:
    - cron: "*/5 * * * *"  # Se ejecuta cada 3 minutos
  #workflow_dispatch:  # Permite ejecutar manualmente

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt || echo "No hay dependencias que instalar"

      - name: Ejecutar script
        run: python PLOT_PG_EFM_ICA_SWP_GITHUB_GRUPO_3.py

      - name: Commit y push si hay cambios
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          # 🔹 Forzar que Git siempre considere la imagen como cambiada
          git add --force PG_ICA_SWP_GRUPO_3.jpg
          
          # 🔹 Intentar hacer commit solo si hay cambios
          git commit -m "Forzando actualización de imagen $(date)" || echo "No hay cambios para commitear"
          
          # 🔹 Hacer push de los cambios
          git push origin main
